export {default as LoginPage} from './components/auth/sign-in/Login'
export {default as HomePage} from './components/home/HomeMain'
export {default as UserPage} from './components/user/User'
export {default as UserDetailPage} from './components/user-detail/UserDetail'
export {default as BookingDetailPage} from './components/booking-detail/BookingDetailMain'
export {default as WorkerPage} from './components/worker/WorkerMain'
export {default as AddWorkerPage} from './components/add-worker/AddWorkerMain'
export {default as WorkerDetailPage} from './components/worker-detail/WorkerDetailMain'
export {default as AddServiceListPage} from './components/add-service/AddServiceMain'
export {default as QuotationPage} from './components/quotations/QuotationMain'
export {default as QuotationDetailPage} from './components/quotation-detail/QuotationDetailMain'
export {default as CompletedServicePage} from './components/complete-services/CompleteServiceMain'
export {default as ProfilePage} from './components/my-profile/Profile'
export {default as ChangePasswordPage} from './components/change-password/ChangePasswordMain'

export {default as CategoryMainPage} from './components/category/CategoryMain'
